const Service = require("../models/Service");
const slugify = require("slugify");

// ✅ Helper Response
const sendResponse = (res, status, message, data = null) => {
  return res.status(status).json({
    success: status < 400,
    message,
    data
  });
};

// ✅ GET ALL SERVICES (with filtering)
exports.getAllServices = async (req, res) => {
  try {
    const { category, status = 'active', limit = 20, skip = 0 } = req.query;

    let filter = { status };

    // Category filter
    if (category) {
      filter.category = category;
    }

    const services = await Service.find(filter)
      .limit(parseInt(limit))
      .skip(parseInt(skip))
      .sort({ created_at: -1 });

    const total = await Service.countDocuments(filter);

    return sendResponse(res, 200, "Services fetched successfully", {
      services,
      pagination: {
        total,
        limit: parseInt(limit),
        skip: parseInt(skip),
        hasMore: parseInt(skip) + parseInt(limit) < total
      }
    });
  } catch (error) {
    return sendResponse(res, 500, "Server error", error.message);
  }
};

// ✅ GET SINGLE SERVICE BY SLUG
exports.getServiceBySlug = async (req, res) => {
  try {
    const { slug } = req.params;

    // ✅ Validate slug
    if (!slug) {
      return sendResponse(res, 400, "Service slug is required");
    }

    const service = await Service.findOne({ slug, status: 'active' });

    if (!service) {
      return sendResponse(res, 404, "Service not found");
    }

    return sendResponse(res, 200, "Service fetched successfully", service);
  } catch (error) {
    return sendResponse(res, 500, "Server error", error.message);
  }
};

// ✅ CREATE SERVICE
exports.createService = async (req, res) => {
  try {
    const { title, description, details, category, price, icon, image_url, features } = req.body;

    // ✅ Validate required fields
    if (!title || !description || !details) {
      return sendResponse(res, 400, "Title, description, and details are required");
    }

    // ✅ Check if title already exists
    const existingService = await Service.findOne({ title });
    if (existingService) {
      return sendResponse(res, 400, "Service with this title already exists");
    }

    // ✅ Create service
    const newService = new Service({
      title,
      description,
      details,
      category,
      price,
      icon,
      image_url,
      features: features || [],
      status: 'active'
    });

    await newService.save();

    return sendResponse(res, 201, "Service created successfully", newService);
  } catch (error) {
    return sendResponse(res, 500, "Server error", error.message);
  }
};

// ✅ UPDATE SERVICE
exports.updateService = async (req, res) => {
  try {
    const { id } = req.params;
    const updateData = req.body;

    // ✅ Validate ID
    if (!id) {
      return sendResponse(res, 400, "Service ID is required");
    }

    // ✅ Check if service exists
    const existingService = await Service.findById(id);
    if (!existingService) {
      return sendResponse(res, 404, "Service not found");
    }

    // ✅ Validate fields (basic)
    if (updateData.title && updateData.title.length < 3) {
      return sendResponse(res, 400, "Title must be at least 3 characters");
    }

    // ✅ Prevent invalid status
    if (updateData.status && !["active", "inactive"].includes(updateData.status)) {
      return sendResponse(res, 400, "Invalid status value");
    }

    // ✅ Update service (slug will be auto-generated by middleware)
    const updatedService = await Service.findByIdAndUpdate(
      id,
      updateData,
      {
        new: true,
        runValidators: true
      }
    );

    return sendResponse(res, 200, "Service updated successfully", updatedService);
  } catch (error) {
    return sendResponse(res, 500, "Server error", error.message);
  }
};

// ✅ DELETE SERVICE
exports.deleteService = async (req, res) => {
  try {
    const { id } = req.params;

    // ✅ Validate ID
    if (!id) {
      return sendResponse(res, 400, "Service ID is required");
    }

    // ✅ Check if service exists
    const service = await Service.findById(id);
    if (!service) {
      return sendResponse(res, 404, "Service not found");
    }

    // ✅ Delete service
    await Service.findByIdAndDelete(id);

    return sendResponse(res, 200, "Service deleted successfully");
  } catch (error) {
    return sendResponse(res, 500, "Server error", error.message);
  }
};